# Generated by Django 5.2.17 on 2026-09-19 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(default=256, validators=[django.core.validators.MinValueValidator(96), django.core.validators.MaxValueValidator(2048)]),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit_ms',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='points',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
