# Generated by Django 5.2.17 on 2026-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_normalize_existing_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='run_all_tests',
            field=models.BooleanField(default=False, help_text='If true, run all tests for full per-test feedback; else stop at first failure. Scoreboard remains ICPC binary (solved/not).'),
        ),
    ]
