# Generated by Django 5.2.17 on 2026-10-01 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_run_all_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time_limit_ms',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
