# Generated by Django 5.2.17 on 2026-10-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hold_results_until_revealed',
            field=models.BooleanField(default=False, help_text='Keep the scoreboard frozen after the end until an admin reveals it.'),
        ),
        migrations.AddField(
            model_name='contest',
            name='results_revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='extra_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
