# Generated by Django 5.2.17 on 2026-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_freeze_hold_and_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='practice_after_end',
            field=models.BooleanField(default=False, help_text='After the contest, anyone who could see it may practice its problems.'),
        ),
    ]
