# Generated by Django 5.2.17 on 2026-09-19 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('language', models.CharField(choices=[('java', 'Java')], default='java', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Judging', 'Judging'), ('Accepted', 'Accepted'), ('WrongAnswer', 'Wrong Answer'), ('TimeLimitExceeded', 'Time Limit Exceeded'), ('MemoryLimitExceeded', 'Memory Limit Exceeded'), ('RuntimeError', 'Runtime Error'), ('CompileError', 'Compile Error')], db_index=True, default='Pending', max_length=32)),
                ('compile_error', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('Pending', 'Pending'), ('Judging', 'Judging'), ('Accepted', 'Accepted'), ('WrongAnswer', 'Wrong Answer'), ('TimeLimitExceeded', 'Time Limit Exceeded'), ('MemoryLimitExceeded', 'Memory Limit Exceeded'), ('RuntimeError', 'Runtime Error'), ('CompileError', 'Compile Error')], max_length=32)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_used_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('stdout_snippet', models.TextField(blank=True, default='')),
                ('stderr_snippet', models.TextField(blank=True, default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='problems.testcase')),
            ],
            options={
                'ordering': ['test_case__order', 'id'],
                'unique_together': {('submission', 'test_case')},
            },
        ),
    ]
