# Generated by Django 5.2.17 on 2026-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='auto_rejudges',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='enqueued_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='judge_claim',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='judging_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Judging', 'Judging'), ('Accepted', 'Accepted'), ('WrongAnswer', 'Wrong Answer'), ('TimeLimitExceeded', 'Time Limit Exceeded'), ('MemoryLimitExceeded', 'Memory Limit Exceeded'), ('RuntimeError', 'Runtime Error'), ('CompileError', 'Compile Error'), ('SystemError', 'System Error')], db_index=True, default='Pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='verdict',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Judging', 'Judging'), ('Accepted', 'Accepted'), ('WrongAnswer', 'Wrong Answer'), ('TimeLimitExceeded', 'Time Limit Exceeded'), ('MemoryLimitExceeded', 'Memory Limit Exceeded'), ('RuntimeError', 'Runtime Error'), ('CompileError', 'Compile Error'), ('SystemError', 'System Error')], max_length=32),
        ),
    ]
