# Generated by Django 5.2.17 on 2026-10-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_judge_reliability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Judging', 'Judging'), ('Accepted', 'Accepted'), ('WrongAnswer', 'Wrong Answer'), ('TimeLimitExceeded', 'Time Limit Exceeded'), ('MemoryLimitExceeded', 'Memory Limit Exceeded'), ('RuntimeError', 'Runtime Error'), ('OutputLimitExceeded', 'Output Limit Exceeded'), ('CompileError', 'Compile Error'), ('SystemError', 'System Error')], db_index=True, default='Pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='submissionresult',
            name='verdict',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Judging', 'Judging'), ('Accepted', 'Accepted'), ('WrongAnswer', 'Wrong Answer'), ('TimeLimitExceeded', 'Time Limit Exceeded'), ('MemoryLimitExceeded', 'Memory Limit Exceeded'), ('RuntimeError', 'Runtime Error'), ('OutputLimitExceeded', 'Output Limit Exceeded'), ('CompileError', 'Compile Error'), ('SystemError', 'System Error')], max_length=32),
        ),
    ]
